const assert = require("assert");
const {
  ATTENDANCE_PLACE_OPTIONS,
  decorateAttendanceSchema,
  validateAttendanceSchemas,
  validateAttendanceEvidence,
  buildAttendanceFollowUp,
} = require("../attendance");
const { buildPublicationPlan, executionTargetKey, executionRecordValues } = require("../task-publisher");

const text = (value) => [{ type: "text", text: String(value) }];
const select = (value) => [{ text: String(value) }];

function schemas() {
  return [
    { itemId: "photo", itemName: "正面照", status: "ready", required: true, order: 1, resultSheetTitle: "13_考勤结果", resultRelationField: "执行记录", fields: [{ key: "photo", label: "正面照", inputType: "image" }] },
    { itemId: "work", itemName: "工作内容收集", status: "ready", required: true, order: 2, resultSheetTitle: "13_考勤结果", resultRelationField: "执行记录", fields: [
      { key: "work", label: "工作内容", inputType: "textarea" },
      { key: "customer", label: "当前客户名称", inputType: "text" },
      { key: "place", label: "当前所在地", inputType: "singleChoice" },
    ] },
  ];
}

function testSchemaPolicy() {
  const decorated = schemas().map(decorateAttendanceSchema);
  validateAttendanceSchemas(decorated, true);
  assert.strictEqual(decorated[0].fields[0].camera, "front");
  assert.strictEqual(decorated[0].fields[0].maxImages, 1);
  assert.strictEqual(decorated[0].fields[0].resultFieldTitle, "正面照片");
  assert.deepStrictEqual(decorated[1].fields.find((field) => field.label === "当前所在地").options, ATTENDANCE_PLACE_OPTIONS);
  assert.throws(() => validateAttendanceSchemas(decorated, false), (error) => error.code === "ATTENDANCE_LOCATION_REQUIRED");
  const item = { attendanceRole: "photo", schemaSnapshot: decorated[0] };
  validateAttendanceEvidence(item, { photo: ["cloud://watermarked"] }, { photo: { originalFileIds: ["cloud://original"], watermarkedFileIds: ["cloud://watermarked"], capturedAt: "2026-08-29 09:00:00", address: "佛山总部" } });
  assert.throws(() => validateAttendanceEvidence(item, { photo: ["cloud://watermarked"] }, {}), (error) => error.code === "ATTENDANCE_PHOTO_EVIDENCE_INVALID");
}

function testPersonTargetPublication() {
  const publication = { record_id: "publish-attendance", values: {
    "任务名称": text("临时考勤抽查"), "任务类型": ["type-attendance"], "执行人员": ["person-a", "person-b"], "任务项": ["photo", "work"],
    "开始时间": String(Date.parse("2026-08-29T09:00:00+08:00")), "截止时间": String(Date.parse("2026-08-29T18:00:00+08:00")),
    "确认发布": true, "发布状态": select("已发布"), "需要定位": true,
    "自动任务唯一键": text("ATTENDANCE_FOLLOW_UP:source-task"),
  } };
  const people = ["a", "b"].map((suffix) => ({ record_id: `person-${suffix}`, values: { "企业微信账号ID（自动）": text(`Sales${suffix.toUpperCase()}`), "姓名（自动）": text(`业务员${suffix.toUpperCase()}`) } }));
  const plan = buildPublicationPlan({
    publication, stores: [], people,
    taskTypes: [{ id: "type-attendance", code: "ATTENDANCE_CHECK", name: "考勤抽查", objectType: "人员" }],
    schemas: schemas(), executionRecords: [],
  });
  assert.strictEqual(plan.instances.length, 2);
  assert.deepStrictEqual(plan.instances.map((instance) => instance.executorRecordIds), [["person-a"], ["person-b"]]);
  assert(plan.instances.every((instance) => instance.locationMode === "record_only"));
  assert(plan.instances.every((instance) => instance.autoGenerated && instance.attendanceGeneration === 1 && instance.sourceAttendanceTaskId === "source-task"));
  assert.strictEqual(executionTargetKey(plan.instances[0]), "person:person-a");
}

function testDirectWecomUserPublication() {
  const publication = { record_id: "publish-direct-user", values: {
    "任务名称": text("直接成员考勤抽查"), "任务类型": ["type-attendance"],
    "执行人员": [{ user_id: "SalesA", name: "业务员A" }, { user_id: "SalesB", name: "业务员B" }],
    "任务项": ["photo", "work"],
    "开始时间": String(Date.parse("2026-08-29T09:00:00+08:00")), "截止时间": String(Date.parse("2026-08-29T18:00:00+08:00")),
    "确认发布": true, "发布状态": select("已发布"), "需要定位": true,
  } };
  const plan = buildPublicationPlan({
    publication, stores: [], people: [],
    taskTypes: [{ id: "type-attendance", code: "ATTENDANCE_CHECK", name: "考勤抽查", objectType: "人员" }],
    schemas: schemas(), executionRecords: [],
  });

  assert.deepStrictEqual(plan.executorUserIds, ["SalesA", "SalesB"]);
  assert.deepStrictEqual(plan.personRecordIds, []);
  assert.deepStrictEqual(plan.instances.map((instance) => instance.targetKey), ["person:SalesA", "person:SalesB"]);
  assert(plan.instances.every((instance) => instance.executorRecordIds.length === 1 && !instance.executorRecordIds[0]));
  assert.deepStrictEqual(executionRecordValues(plan.instances[0])["执行人员"], [{ user_id: "SalesA" }]);
}

function testRoadFollowUp() {
  const submittedAt = "2026-08-29T10:10:00+08:00";
  const followUp = buildAttendanceFollowUp({ id: "task-a", name: "上午考勤", status: "completed", items: [{ id: "photo", status: "completed" }], attendancePlace: "在路上", attendanceFollowUpPending: true }, submittedAt);
  assert.strictEqual(followUp.startAt, "2026-08-29T02:25:00.000Z");
  assert.strictEqual(followUp.deadlineAt, "2026-08-29T15:59:00.000Z");
  assert.strictEqual(followUp.attendanceGeneration, 1);
  assert.strictEqual(followUp.attendanceFollowUpPending, false);
  assert.strictEqual(followUp.items[0].status, "pending");
}

testSchemaPolicy();
testPersonTargetPublication();
testDirectWecomUserPublication();
testRoadFollowUp();
console.log("attendance tests passed");
