const assert = require("assert");
const fs = require("fs");
const path = require("path");

const pageRoot = path.resolve(__dirname, "../../../miniprogram/pages/sampling");
const script = fs.readFileSync(path.join(pageRoot, "index.js"), "utf8");
const template = fs.readFileSync(path.join(pageRoot, "index.wxml"), "utf8");
const apiScript = fs.readFileSync(path.resolve(__dirname, "../../../miniprogram/utils/api.js"), "utf8");
const wecomScript = fs.readFileSync(path.resolve(__dirname, "../wecom.js"), "utf8");
const proxyScript = fs.readFileSync(path.resolve(__dirname, "../../../../sfa-proxy/server.js"), "utf8");

assert.match(script, /productTotal: products\.length/);
assert.match(script, /buildGroupNavigation/);
assert.match(script, /toggleSection/);
assert.match(script, /toggleProduct/);
assert.match(script, /defaultExpandedProducts/);
assert.match(script, /readOnly/);
assert.match(script, /queueAutoSave/);
assert.match(script, /preSyncImages: true/);
assert.match(script, /buildSaveAlert/);
assert.match(script, /showAutoSaveNotice/);
assert.match(script, /completeTaskItem[\s\S]*silent: true/);
assert.doesNotMatch(template, /productRule\.ruleName/);
assert.doesNotMatch(template, /group-heading/);
assert.match(template, /section\.level1Name/);
assert.match(template, /child\.level2Name/);
assert.match(template, /共 \{\{child\.productTotal\}\} 款/);
assert.match(template, /child\.progressText/);
assert.match(template, /child\.qualified/);
assert.match(template, /class="group-check"/);
assert.match(template, /groups\[activeGroup\]\.ruleText/);
assert.match(template, /groups\[activeGroup\]\.reportedProducts/);
assert.match(template, /groups\[activeGroup\]\.qualificationText/);
assert.doesNotMatch(template, /必分销/);
assert.doesNotMatch(script, /不限制业务总数/);
assert.match(template, /expandedProducts\[item\.id\]/);
assert.doesNotMatch(template, /补充产品/);
assert.doesNotMatch(template, /supplementExpanded/);
assert.match(template, /上传照片/);
assert.match(template, /autoSaveNotice\.visible/);
assert.match(template, /saveAlert\.visible/);
assert.match(template, /save-alert-content/);
assert.match(template, /去处理/);
assert.match(template, /readOnly/);
assert.doesNotMatch(template, /class="nav-save"/);
assert.match(apiScript, /wx\.compressImage/);
assert.match(apiScript, /quality \|\| 85/);
assert.match(wecomScript, /new https\.Agent\(\{ keepAlive: true/);
assert.match(proxyScript, /WECOM_HTTPS_AGENT/);
process.stdout.write("sampling page contract tests passed\n");
